# -*- coding: utf-8 -*-
"""PROJECT(MIC).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Dsk2RYWErnEd9vmRC2cNKYPtWbazia8q
"""

pip install datasets

!pip install -U datasets transformers torchvision

import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import transforms
from datasets import load_dataset
from transformers import ViTForImageClassification, ViTFeatureExtractor
from torch.utils.data import DataLoader, Dataset
import torch.nn.functional as F
from torch.cuda.amp import GradScaler, autocast

from datasets import load_dataset
from transformers import ViTFeatureExtractor
from torchvision import transforms

# Load dataset without streaming
dataset = load_dataset("funkepal/medicinal_plant_images")  # Removed streaming=True

# Load ViT feature extractor
feature_extractor = ViTFeatureExtractor.from_pretrained("google/vit-base-patch16-224")

# Define image transform
transform = transforms.Compose([
    transforms.Resize((224, 224)),  # Resize to 224x224 for ViT
    transforms.RandomResizedCrop(224),
    transforms.RandomHorizontalFlip(),
    transforms.Lambda(lambda img: img.convert("RGB")),  # Ensure RGB
    transforms.ToTensor(),
    transforms.Normalize(mean=feature_extractor.image_mean, std=feature_extractor.image_std)
])

# Custom dataset class to handle transformations
class PlantDataset(Dataset):
    def __init__(self, data, transform):
        self.data = data
        self.transform = transform

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        item = self.data[idx]
        image = item['image']
        label = item['label']

        # Apply the transformation to the image
        image = self.transform(image)
        return image, torch.tensor(label, dtype=torch.long)



# Apply the transformation using the custom dataset class
# Use the loaded dataset object (dataset_obj) instead of the string variable (dataset)
train_dataset = PlantDataset(dataset['train'], transform)
test_dataset = PlantDataset(dataset['test'], transform)

# DataLoader for batching and shuffling
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)  # Adjust batch size as needed
test_loader = DataLoader(test_dataset, batch_size=32, shuffle=False)

# Define CNN for Feature Extraction
class CNNFeatureExtractor(nn.Module):
    def __init__(self):
        super(CNNFeatureExtractor, self).__init__()
        self.conv_layer = nn.Sequential(
            nn.Conv2d(3, 64, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2),
            nn.Conv2d(64, 128, kernel_size=3, stride=1, padding=1),
            nn.ReLU(),
            nn.MaxPool2d(kernel_size=2, stride=2)
        )

    def forward(self, x):
        x = self.conv_layer(x)
        return x

# Instantiate CNN feature extractor
cnn_extractor = CNNFeatureExtractor()

# Vision Transformer for Classification
class HybridModel(nn.Module):
    def __init__(self):
        super(HybridModel, self).__init__()
        self.cnn = cnn_extractor
        self.vit = ViTForImageClassification.from_pretrained(
            "google/vit-base-patch16-224",
            num_labels=41,  # Number of classes in your dataset
            ignore_mismatched_sizes=True  # Add this line to ignore size mismatches
        )
        self.conv_proj = nn.Conv2d(128, 3, kernel_size=1)  # Define the projection layer here

    def forward(self, x):
        # Extract features using CNN
        x = self.cnn(x)
        # Resize features to 224x224 for ViT using interpolation
        x = F.interpolate(x, size=(224, 224), mode='bilinear', align_corners=False)
        # Project features to 3 channels using a 1x1 convolution
        x = self.conv_proj(x)  # Use the defined projection layer
        outputs = self.vit(pixel_values=x)  # Use Vision Transformer for classification
        return outputs.logits

# Instantiate the model
model = HybridModel()

# Optimizer and Loss Function
optimizer = optim.Adam(model.parameters(), lr=1e-4)
criterion = nn.CrossEntropyLoss()

# Device configuration
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Mixed Precision Training
scaler = GradScaler()  # Mixed precision scaler

# Training the Model
def train(model, train_loader, optimizer, criterion, device, scaler):
    model.train()
    total_loss = 0
    correct = 0

    for images, labels in train_loader:
        images = images.to(device)
        labels = labels.to(device)

        optimizer.zero_grad()  # Clear gradients

        with autocast():  # Mixed precision
            outputs = model(images)  # Forward pass
            loss = criterion(outputs, labels)  # Calculate loss

        scaler.scale(loss).backward()  # Backpropagation with scaled gradients
        scaler.step(optimizer)  # Update weights
        scaler.update()

        total_loss += loss.item()  # Accumulate loss
        correct += (outputs.argmax(1) == labels).sum().item()  # Count correct predictions

        torch.cuda.empty_cache()  # Free up GPU memory

    accuracy = correct / len(train_loader.dataset)
    return total_loss / len(train_loader), accuracy  # Return average loss and accuracy

# Evaluation function
def evaluate(model, test_loader, criterion, device):
    model.eval()
    total_loss = 0
    correct = 0

    with torch.no_grad():
        for images, labels in test_loader:
            images = images.to(device)
            labels = labels.to(device)

            outputs = model(images)  # Forward pass
            loss = criterion(outputs, labels)  # Calculate loss
            total_loss += loss.item()
            correct += (outputs.argmax(1) == labels).sum().item()  # Calculate accuracy

            torch.cuda.empty_cache()  # Free up GPU memory

    accuracy = correct / len(test_loader.dataset)
    return total_loss / len(test_loader), accuracy  # Return average loss and accuracy

# Train and evaluate the model
num_epochs = 10
total_train_loss = 0
total_test_loss = 0

for epoch in range(num_epochs):
    print(f"Epoch {epoch + 1}/{num_epochs}")

    # Training phase
    train_loss, train_accuracy = train(model, train_loader, optimizer, criterion, device, scaler)
    print(f"Train Loss: {train_loss:.4f}, Train Accuracy: {train_accuracy:.4f}")

    # Testing phase
    test_loss, test_accuracy = evaluate(model, test_loader, criterion, device)
    print(f"Test Loss: {test_loss:.4f}, Test Accuracy: {test_accuracy:.4f}")

    # Accumulate losses (not accuracies) if you need them for reference
    total_train_loss += train_loss
    total_test_loss += test_loss

# Print final total loss and accuracy after all epochs
print(f"\nTotal Training Loss after {num_epochs} epochs: {total_train_loss:.4f}")
print(f"Total Test Loss after {num_epochs} epochs: {total_test_loss:.4f}")
print(f"Final Training Accuracy after {num_epochs} epochs: {train_accuracy:.4f}")  # Final epoch accuracy
print(f"Final Test Accuracy after {num_epochs} epochs: {test_accuracy:.4f}")  # Final epoch accuracy



# Load the dataset from Hugging Face
from datasets import load_dataset
dataset = load_dataset("funkepal/medicinal_plant_images")

# Get the feature information (label mapping)
label_names = dataset['train'].features['label'].names

# Print the label names
print(f"\nThere are {len(label_names)} unique image class names:")
for idx, label in enumerate(label_names):
    print(f"Label {idx}: {label}")

# Optionally, inspect the structure of an individual sample (e.g., the first image and label)
first_sample = dataset['train'][0]
label_of_first_sample = label_names[first_sample['label']]

print(f"\nExample sample from dataset:")
print(f"Image: {first_sample['image']} \nLabel: {label_of_first_sample}")

# Count the occurrences of each class in the dataset using the label names
from collections import Counter

# Create a Counter for the labels (mapped to their names)
label_counts = Counter(label_names[item['label']] for item in dataset['train'])

print("\nLabel Distribution (Count of each class in the training set):")
for label, count in label_counts.items():
    print(f"{label}: {count} images")

from PIL import Image
import torch
from torchvision import transforms
import matplotlib.pyplot as plt

# Preprocess function for the new image
def preprocess_image(image_path, feature_extractor):
    image = Image.open(image_path).convert('RGB')  # Convert image to RGB

    # Define the transformations (resize, convert to tensor, normalize)
    transform = transforms.Compose([
        transforms.Resize((224, 224)),  # Resize to the required input size for the model
        transforms.ToTensor(),  # Convert the image to tensor
        transforms.Normalize(mean=feature_extractor.image_mean, std=feature_extractor.image_std)
    ])

    transformed_image = transform(image).unsqueeze(0)  # Add batch dimension
    return transformed_image, image  # Return both the tensor and original image for display

# ... (rest of your code)
# Function to classify an image using the model
def classify_image(model, image_tensor, device):
    model.eval()  # Set the model to evaluation mode
    image_tensor = image_tensor.to(device)  # Move the image tensor to the same device as the model

    with torch.no_grad():
        outputs = model(image_tensor)  # Forward pass through the model
        # Directly use outputs without logits attribute
        predicted_class_idx = torch.argmax(outputs, dim=1).item()  # Get the predicted class index

    return predicted_class_idx

# Load and preprocess the new image
image_path = '/content/aar2.jpg' # Specify the path to your new image
image_tensor, original_image = preprocess_image(image_path, feature_extractor)

# Load the model and move it to the same device (CPU or GPU)
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model.to(device)

# Classify the new image
predicted_class_idx = classify_image(model, image_tensor, device)

# Get the actual label name from the predicted class index
predicted_label = label_names[predicted_class_idx]

# Display the original image and the predicted class
plt.imshow(original_image)
plt.title(f"Predicted Label: {predicted_label}")
plt.axis('off')
plt.show()

# Print the result
print(f"The model predicts the image is of: {predicted_label}")

# Access the first item from the test dataset
test_image, true_label = test_dataset[20]

# Convert the tensor back to a PIL-compatible format for visualization
image_np = test_image.permute(1, 2, 0).numpy()  # Convert CHW to HWC
image_np = (image_np * [0.229, 0.224, 0.225]) + [0.485, 0.456, 0.406]  # Unnormalize
image_np = image_np.clip(0, 1)  # Ensure pixel values are within [0, 1]

# Plot the image
import matplotlib.pyplot as plt
plt.imshow(image_np)
plt.axis("off")
plt.title(f"True Label: {true_label}")
plt.show()

# Access the first item from the test dataset
test_image, true_label = test_dataset[20]

# Prepare the image for the model (add batch dimension)
test_image_batch = test_image.unsqueeze(0)  # Shape: [1, C, H, W]

# Move the input to the same device as the model
test_image_batch = test_image_batch.to(device)

# Predict the label using the model
model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    output = model(test_image_batch)
    predicted_label = torch.argmax(output, dim=1).item()  # Get the predicted class index

# Print the predicted label
print(f"Predicted Label: {predicted_label}")
print(f"True Label: {true_label}")

import matplotlib.pyplot as plt
from torchvision import transforms

# Access the first item from the test dataset
test_image, true_label = test_dataset[20]

# Prepare the image for the model (add batch dimension)
test_image_batch = test_image.unsqueeze(0)  # Shape: [1, C, H, W]

# Move the input to the same device as the model
test_image_batch = test_image_batch.to(device)

# Predict the label using the model
model.eval()  # Set the model to evaluation mode
with torch.no_grad():
    output = model(test_image_batch)
    predicted_label_index = torch.argmax(output, dim=1).item()  # Get the predicted class index

# Get the predicted label name
predicted_label_name = label_names[predicted_label_index]

# Denormalize the image for visualization
# (Assuming you've defined 'mean' and 'std' for your normalization)
inv_normalize = transforms.Normalize(
    mean=[-m / s for m, s in zip(feature_extractor.image_mean, feature_extractor.image_std)],
    std=[1 / s for s in feature_extractor.image_std]
)
denormalized_image = inv_normalize(test_image)

# Convert the tensor back to a PIL-compatible format for visualization
image_np = denormalized_image.permute(1, 2, 0).cpu().numpy()  # Convert CHW to HWC
image_np = image_np.clip(0, 1)  # Ensure pixel values are within [0, 1]

# Plot the image
plt.imshow(image_np)
plt.axis("off")
plt.title(f"Predicted Label: {predicted_label_name}, True Label: {label_names[true_label.item()]}")
plt.show()

import matplotlib.pyplot as plt
from torchvision import transforms

# Step 5: Select a test image
test_image_info = test_dataset[20]  # Use the first image in the test dataset
image = test_image_info[0] # Access the image using numerical index 0
label = test_image_info[1]  # Access the label using numerical index 1

# The image is already a tensor, no need to apply transform again
input_image = image.unsqueeze(0)  # Add batch dimension if needed

# Step 6: Predict the label
with torch.no_grad():
    output = model(input_image.to(device)) # Ensure input is on the correct device
    predicted_label = torch.argmax(output, dim=1).item()

# Step 7: Display the image and predicted label
# Denormalize the image before converting to PIL Image
mean = feature_extractor.image_mean
std = feature_extractor.image_std

# Create an inverse transform to reverse the normalization
inv_normalize = transforms.Normalize(
    mean=[-m / s for m, s in zip(mean, std)],
    std=[1 / s for s in std]
)

# Denormalize the image
denormalized_image = inv_normalize(image)

# Convert the denormalized image tensor to a PIL Image for display
image_to_display = transforms.ToPILImage()(denormalized_image)

plt.imshow(image_to_display)
plt.axis("off")
plt.title(f"Predicted Label: {predicted_label}, True Label: {label}")
plt.show()

# Access the first item from the test dataset
test_image, _ = test_dataset[20]

# Convert the tensor back to a PIL-compatible format for visualization
image_np = test_image.permute(1, 2, 0).numpy()  # Convert CHW to HWC
image_np = (image_np * [0.229, 0.224, 0.225]) + [0.485, 0.456, 0.406]  # Unnormalize
image_np = image_np.clip(0, 1)  # Ensure pixel values are within [0, 1]

# Plot the image
import matplotlib.pyplot as plt
plt.imshow(image_np)
plt.axis("off")
plt.show()

import matplotlib.pyplot as plt
from torchvision import transforms
from datasets import load_dataset # Import load_dataset



# Step 7: Test a single image from the test dataset
test_image, true_label = test_dataset[20]  # Use the first image in the test dataset
test_image_batch = test_image.unsqueeze(0)  # Add batch dimension

# Reload the dataset to get label names (or define them explicitly if known)
dataset = load_dataset("funkepal/medicinal_plant_images") # Reload dataset
label_names = dataset['train'].features['label'].names # Get label names

# Step 8: Predict the label
with torch.no_grad():
    # Move the input tensor to the same device as the model
    output = model(test_image_batch.to(device))
    predicted_label_index = torch.argmax(output, dim=1).item()  # Get the predicted label index
    predicted_label_name = label_names[predicted_label_index] # Get the corresponding label name

# Step 9: Visualize the image and the predicted label
# Convert the tensor back to a PIL image for visualization
test_image_np = test_image.permute(1, 2, 0).numpy()  # Convert CHW to HWC
test_image_np = (test_image_np * [0.229, 0.224, 0.225]) + [0.485, 0.456, 0.406]  # Unnormalize
test_image_np = test_image_np.clip(0, 1)

plt.imshow(test_image_np)
plt.axis("off")
plt.title(f"Predicted Label: {predicted_label_name}, True Label: {label_names[true_label.item()]}") # Use label names for display
plt.show()